---
#
# Custom manifests/addons
# -> We're making sure, that *all* servers have the same files
#
- name: Add manifest files
  include_role:
    name: rke2_common
    tasks_from: add-manifest-addons.yml
  when:
    - manifest_config_file_path is defined
    - manifest_config_file_path | length > 0

- name: Add kube-vip files
  include_role:
    name: rke2_common
    tasks_from: add-kube-vip.yml
  when:
    - kube_vip_enabled | bool

#
# Setup RKE2
#

- name: RKE2 agent and server tasks
  vars:
    caller_role_name: server
  include_role:
    name: rke2_common
    tasks_from: main

- name: Setup initial server
  include_tasks: first_server.yml
  when: inventory_hostname in groups['rke2_servers'][0]

- name: Setup other servers
  include_tasks: other_servers.yml
  when: inventory_hostname in groups['rke2_servers'][1:]
